config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  post   'signup',  to: 'users#create'
  post   'spectate',  to: 'games#watch'
  resources :users
  resources :games do
    member do
      post 'join'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  has_many :game_users
  has_many :games, through: :game_users

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to '/games'
    else
      flash[:danger] = "Invalid Input"
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.name.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/new.slim
- provide(:title, "Account")
h1.welcome Create Account

body
  img class="card_picture" src="https://www.partyswizzle.com/assets/images/03Food/NapkinsCardSuits.jpg" alt="A Picture of Four Aces" 
  .row
    .col-md-6.col-md-offset-3
      = form_for(@user, url: signup_path) do |f|
        = f.label :name
        = f.text_field :name

        = f.label :password
        = f.password_field :password

        = f.label :password_confirmation
        = f.password_field :password_confirmation

        = f.submit "Sign Up", class: "btn btn-yellow"
        
      p Already Have An Account?
      = link_to "Sign In", login_path, class: "btn btn-brown"

app/views/users/show.slim
- provide(:title, @user.name)
body

  .container
    h1
      = gravatar_for @user
      = @user.name
  .container
    h4.stats-header Player Stats
  .container.stats_container
    .no_margin
      p.list-stats Games Won: 0
    .no_margin
      p.list-stats Games Lost: 0
    .no_margin
      p.list-stats Percentage: 0%
  .container.btn-lobby
    = link_to "Lobby", games_url, class: "btn btn-yellow"