config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  post   'signup',  to: 'users#create'
  post   'spectate',  to: 'games#watch'
  resources :users
  resources :games do
    member do
      post 'join'
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  attr_accessor :player_num, :players, :hand
  serialize :go_fish, GoFish
  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true

  has_many :game_users
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
    @session_player = @game.go_fish.find_player_by_name(current_user.name)
  end

  def create
    @game = Game.new(game_params)
    player = Player.new(current_user.name)
    @game.go_fish = GoFish.new(@game.name, players: [player], player_num: game_params[:player_num])
    if @game.save
      @session_player = @game.go_fish.find_player_by_name(current_user.name)
      game_user = GameUser.create(game: @game, user: current_user)
      flash[:success] = "Game Successfully Created"
      redirect_to game_path(@game)
    else
      flash[:danger] = "Game Not Created"
      render :new
    end
  end

  def join
    @game = Game.find(params[:id])
    game_user = GameUser.create(game: @game, user: current_user)
    game_data = @game.go_fish
    player = Player.new(current_user.name)
    @session_player = @game.go_fish.find_player_by_name(current_user.name)
    game_data.add_player(player)
    @game.save
    redirect_to game_path(@game)
  end

  def update
    @game = Game.find(params[:id])
    @session_player = @game.go_fish.find_player_by_name(current_user.name)
    @card = turn_params[:hand]
    @player = @game.go_fish.find_player_by_name(turn_params[:players])
    @game.go_fish.take_turn(@session_player, @player, @card)
    @game.save
    redirect_to game_path(@game)
  end

  def watch
    render :watch
  end

  private 

  def game_params
    params.require(:game).permit(:name, :player_num)
  end

  def turn_params
    params.require(:game).permit(:hand, :players)
  end
end

app/views/games/index.slim
body 
  h1 Pending Games
  .flex
    - @games.each do |game|
      .flex-column
        p.flex.game-item = game.name
        .row
          = button_to "Join", join_game_path(game.id), class: "btn btn-join"
        .row
          = button_to "Spectate", spectate_path, class: "btn btn-spectate"
  = link_to "Create Game", new_game_path, class: "btn btn-yellow"
  = link_to "Logout", logout_path, class: "btn btn-yellow", method: :delete

app/views/games/new.slim
- provide(:title, "Create Game")

body

  h1 Create A Game
  = form_for(@game) do |f|
  
    = f.label :name
    = f.text_field :name

    - (2..6).each do |number|
      = f.radio_button :player_num, number, class: "btn-#{number}-players"
      = f.label :player_num, "#{number} Players", value: number

    = f.submit "Create Game", class: "btn btn-primary"

app/views/games/show.slim
section
  .flex.flex-row.top-box
    ul.player-list
      - @game.go_fish.players.each do |player|
        li.flex.player__box.player__list--text data-test-id="player1"
          - if current_user.name == player.name
            b = "#{player.name} #{player.hand.count}"
          - else
            = "#{player.name} #{player.hand.count}"
    .matches-header
      p = "Matches:"
      .stats
        - @game.go_fish.players.each do |player|
          li.flex.player-stats
            = "#{player.name}: #{player.completed_matches.count}"
        p.deck_stats = "Cards Left In Deck: #{@game.go_fish.card_deck.cards_left}"
- if @game.go_fish.started == true
  - if @session_player.name == @game.go_fish.current_player.name
    == render "/layouts/popup"
.result_message
  - @game.go_fish.results.each do |message|
    p = message
.flex.your-hand-column
  p.your-info-header Your Cards
.flex.your-hand
  - @session_player.hand.each do |card|
    img.card_image src="/card_faces/#{card.image_name}.jpg" alt="#{card.alt_to_s}"
.flex.your-matches-column
  p.your-info-header Your Matches
.flex.your-matches
  - @session_player.completed_matches.each do |card|
    img.card_image src="/images/card_faces/#{card[0]}H.jpg" alt="#{card.to_s}"
- if @game.go_fish.match_num == 13
  == render "/layouts/win"

app/views/games/watch.slim
section
  .flex.enter-header
    p.flex.enter-header-text Spectate Game
  .flex.flex-row.top-box
    ul.player-list
      - @game.go_fish.players.each do |player|
        li.flex.player__box.player__list--text data-test-id="player-bot1"
          - if current_player.name == player.name
            b = "#{player.name} #{player.hand.count}"
          - else
            = "#{player.name} #{player.hand.count}"
    .flex-row
      p.matches-header = "Matches:"
      .stats
        - game.go_fish.players.each do |player|
          li.flex.player-stats 
            = "#{player.name}: #{player.completed_matches.count}"
        p.deck_stats = "Cards Left In Deck: #{game.card_deck.cards_left}"
      - if current_player.name == game.current_player.name
        a.button href="#popup1" Click To Take Turn
  .result_message
    - game&.results.each do |message|
      p = message
  .flex
    .your-hand-column
      p.your-info-header Your Cards
  .flex
    .your-hand
      - current_player.hand.each do |card|
        img.card_image src="/images/card_faces/#{card.image_name}.jpg" alt="#{card.alt_to_s}"
  .flex
    .your-matches-column
      p.your-info-header Your Matches
  .flex
    .your-matches
      - current_player.completed_matches.each do |card|
        img.card_image src="/images/card_faces/#{card[0]}H.jpg" alt="#{card.to_s}"
    div id="popup1" class="overlay"
      .popup
        h2 Select The Card & Player 
        a.close href="#" &times;
        .content
          form action="/ask" method="post"
            p Choose A Card To Ask For
            - current_player.unique_ranks.each do |rank|
              .flex.card-item.card-btn data-test-id="card-btn1"
                input class="card-list-item" id="rank" type="radio" name="rank" value="#{rank}" #{rank}
            p Choose A Player To Ask
            - game.players.each do |player|
              - if game.current_player.name != player.name
                .flex.player-btn data-test-id="player-btn1"
                  input class="player-list-item" type="radio" id="player" name="player" value="#{player.name}" #{player.name}
            button class="ask-btn" type="submit" Ask
  - if game.match_num == 13
    div id="winscreen" class="win-overlay"
      .win-popup
        h2 Game Scores
        a.close href="#" &times;
        .win-content
          - game.players.each do |player|
            p "#{player.name} #{player.completed_matches}"
          form action="/leave" method="post"
            button class="leave-game-btn" type="submit" Leave Game
          form action="/new" method="post"
            button class="enter-game-btn" type="submit" Start New Game